### ISSUE TITLE
MATES_model.train error

### ISSUE THREAD

**Issue by bio-xtt** [mcgilldinglab/MATES#12]
Hello, my previous code is running normally, but the following error occurs when I run MATES_model.train. How should I solve it?
**code**
`MATES_model.train('10X', 'human_sample_list_file.txt', bin_size = 5, proportion = 80, BATCH_SIZE= 4096, 
                  AE_LR = 1e-4, MLP_LR = 1e-6, AE_EPOCHS = 200, MLP_EPOCHS = 200, DEVICE='cpu')`

**error**
![2024-10-21_09-25](https://github.com/user-attachments/assets/01220f83-0d45-4584-b493-520a645a9362)

**directory**:
![image](https://github.com/user-attachments/assets/9ef293ab-a603-4e26-9e22-c2bc55002d3e)

**Comment by Szym29** [comment]
Hi @bio-xtt ,

Can you check the 'Unique_BATCH_train_5_80.npz' file? It looks like this file is empty. And not only this file, it looks like all files with size= 4kb are empty.

Would you be able to run our [sample data](https://mcgill-my.sharepoint.com/:u:/g/personal/ruohan_wang4_mail_mcgill_ca/EdwyzdHz1KtLr9G_c503mwsB6Y4-lawnqEQ1NBx_1Mn9tQ?e=YkcH1B) using this [sample script](https://github.com/mcgilldinglab/MATES/blob/main/example/sample_pipeline.ipynb)? 

I would suggest you to first check the directory and parameters used to build coverage vector are properly used.

Thanks,
Yumin

**Comment by Szym29** [comment]
hi @bio-xtt ,

This is the output of our sample pipeline.

4.0K    5_80_stat.csv
12K     M&U_5_80%.pkl
4.0K    Multi_Batch_train_5_80.npz
360K    Multi_meta_train_5_80.pkl
32K     Multi_Region_train_5_80.npz
144K    Multi_TE_train_5_80.npz
4.0K    Unique_BATCH_train_5_80.npz
24K     Unique_selected_meta_5_80.pkl
96K     Unique_TE_train_5_80.npz

You can check your input files, parameters, and directory using our example data and pipeline. 

Thanks,
Yumin

**Comment by bio-xtt** [comment]
Is this due to my improper setting of parameters? How should I adjust my parameters in this case?

**Comment by Szym29** [comment]
Hi @bio-xtt ,

If you may, can you share a part of your aligned data with us? Including cell barcode (like the test_cb.tsv file), bam, and bam.bai file. 

Thanks,
Yumin

**Comment by bio-xtt** [comment]
Thank you very much. I captured the cellrannger bam file for each sample chr1:1-1000000 and provided the barcodes.tsv file in the filtered_feature_bc_matrix folder.
**data download link:** 
https://zenodo.org/api/records/13969187/draft/files/test_data.zip/content

**Comment by Szym29** [comment]
Hi,

Please grant the permission for me to access this data. 

Thanks,
Yumin

**Comment by bio-xtt** [comment]
**Can you try this link below?**
https://gofile.io/d/WxRkct

**Comment by Szym29** [comment]
Hi @bio-xtt ,

I checked your example data, and found that only several reads are mapped to the TE regions. In H1 sample, the total number of reads mapped to the TE regions are around 10. This limited number of TE reads is not able to create the training samples. 

Are you using all reads from each cell to run MATES in your end? Since you just shared reads mapped to chr1:1-1000000 with me. To check this issue, you can probably use maybe hundreds of cells with all reads to run MATES. The sample data has only a few cells, but MATES can be applied to it smoothly. So for the debugging purpose, a hundred cells should be enough. Here are my suggestions:
1, sync your code to our latest version. 
2, check the MU_Stats/5_80_stat.csv file produced after running data_processor.calculate_UM_region. This file shows how many reads mapped to each TE family after filtering. 
3. If the number of reads mapped to each TE family is very low, change the cut_off when running data_processor.calculate_UM_region. e.g. `data_processor.calculate_UM_region('exclusive', '10X', 'human_sample_list_file.txt', bin_size=5, proportion=0, bc_path_file='bc_path_file.txt',cut_off=1)` . If you see a reasonable number of reads mapped to each TE family after setting a lower cut_off, then you should be able to build the training data successfully and run the `MATES_model.train`.  (This cut_off parameter is newly implemented, so please update the code.)
4. In the count_coverage/H1/barcodes* folders e.g.  count_coverage/H1/AAACGAACACATACGT-1, you can find two csv files. These two files show how many reads in this bam file are uniquely or multiply mapped to TE regions. You can also check it. 

Please feel free to contact us if you have any further question. 

Thanks,
Yumin

**Comment by bio-xtt** [comment]
Thank you very much. I only intercepted the chr1 part of bam file and compared it with reads. I plan to run it again according to your suggestion, thank you

**Comment by bio-xtt** [comment]
Thank you very much. I only intercepted the chr1 part of bam file and compared it with reads. I plan to run it again according to your suggestion, thank you

**Comment by Szym29** [comment]
Hi @bio-xtt ,

We will release a new function to speed up 10X data preprocessing in the next a few days. I will let you know and then you can try more reads. 

Thanks,
Yumin

**Comment by Szym29** [comment]
Hi @bio-xtt,

Please check our v0.1.3 release. The function `bam_processor.split_count_10X_data()` can help you speed up the preprocessing step. 

The example data you provided with us contains more than 20k cell barcodes, but only a few reads mapped to part of Chr 1. Since preprocessing 20k cells may cost one or two days. For the testing purpose, my suggestion is to extract all reads from one or two hundred cells and run MATES to see if this error can be resolved. 

We tested a few 10X datasets recently, even some data have only 20 to 50 cells, with the default parameters used in the example_pipeline, MATES can run smoothly. 

Thanks,
Yumin
