### ISSUE TITLE
Whether MATES is capable of handling spatial transcriptomics data (eg. 10X visium)

### ISSUE THREAD

**Issue by huangzr123** [mcgilldinglab/MATES#15]
If MATES can detect TE expression using 10X Visium data, I encountered the following question while running the function bam_processor.split_bam_files with the Space Ranger outputs of 10X Visium data:

if data_mode == "10X":
if not bc_path_file:
raise ValueError('Please provide barcodes file for 10X data!')
print("Start splitting multi sub-bam based on cell barcodes...")
script_path = pkg_resources.resource_filename('MATES', 'scripts/split_bc_u.sh')

ValueError: Please provide barcodes file for 10X data!

Thank you for your help!
Kind regards,
Zurui

**Comment by Szym29** [comment]
Hi @huangzr123 ,

I think MATES can process 10X visium data because you can simply treat it as the 10X scRNA-seq if you don't think about their position information. And I don't see differences between the format of bam files from 10X Visium and 10X scRNA-seq.

Basically, you can follow this [10X example](https://github.com/mcgilldinglab/MATES/blob/main/example/sample_pipeline.ipynb)  to process your data 10X Visium bam file. You need to prepare 3 mandatory files, (check them in the MATES/example/ folder):
- sample_list.txt: The file contains sample names, each row represents a sample
- path_to_bam.txt: The file contains the directory to each sample's bam file
- path_to_barcode.txt: The file contains the directory to each sample's cell barcode list.

For the cell barcode list, you can check this example [barcode.tsv](https://github.com/mcgilldinglab/MATES/blob/main/example/test_cb.tsv) file. Each row is a cell barcode (in CR or CB field). The example file uses CR field, but you can use CB.

Then follow our [10X example](https://github.com/mcgilldinglab/MATES/blob/main/example/sample_pipeline.ipynb) to use the newly implemented `bam_processor.split_count_10X_data()` to preprocess the dataset. 

Thanks,
Yumin

**Comment by Szym29** [comment]
Hi @huangzr123 ,

We just tested MATES on the 10X Visium data and it works fine. Please check our [example pipeline](https://github.com/mcgilldinglab/MATES/tree/main/example/10X_visium_example) for 10X Visium dataset. 

Thanks,
Yumin
