### ISSUE TITLE
The duplicated TE_index in h5ad output

### ISSUE THREAD

**Issue by huangzr123** [mcgilldinglab/MATES#18]
Sorry, when I test the h5ad output, I found the TE_index is duplicated?

table(duplicated(CRC4_loci@assays$[RNA@meta.features](mailto:RNA@meta.features)$TE_index))
FALSE TRUE
118628 15414

**Comment by Szym29** [comment]
Hi @huangzr123 ,

This issue has been fixed in the MATES v0.1.4. Please update your code. And re-run `TE_quantifier.quantify_locus_TE_MTX()`. Please provide the csv format TE reference file in this function. e.g. `quantify_locus_TE_MTX('inclusive','10X', 'sample_list.txt',ref_path = './TE_full.csv')`

Thanks,
Yumin
