### ISSUE TITLE
Inquiry About Barcode Selection for scRNA-seq and scATAC-seq in MATES

### ISSUE THREAD

**Issue by Citugulia40** [mcgilldinglab/MATES#24]
Hi,

Thank you for developing MATES; it has been an invaluable tool for my research. This is not an issue report but rather a query regarding data preprocessing for 10x Multiome data.

I am currently preparing to run MATES and have processed my data as follows:

_**For scRNA-seq:**_
I used STARsolo, which generated the `sample_RNAAligned.sortedByCoord.out.bam` file and the `sample_Solo.out` directory containing both raw and filtered barcodes (**Gene/raw/barcodes.tsv** and **Gene/filtered/barcodes.tsv**).
_**For scATAC-seq:**_
Similarly, STARsolo provided the `sample_ATACAligned.sortedByCoord.out.bam` file and a `sample_Solo.out` directory, but only raw barcodes were available (**Gene/raw/barcodes.tsv**). As expected for scATAC-seq, no filtered barcodes were generated since reads typically do not map inside genes.

Given this, I would like your guidance on the following:

- Should barcodes for scATAC-seq be extracted directly from the BAM file? If so, I noticed that this results in a much larger set of barcodes compared to the filtered scRNA-seq barcodes.
- Which barcode files would you recommend using for each modality to ensure compatibility and optimal performance with MATES?

Also, For my dataset with 15 donors, your documentation provides an example of how to structure the `sample_list_file`, `bam_path_file`, and `bc_path_file` for a single donor:

```
sample_list_file:
pbmc_scRNA
pbmc_scATAC

bam_path_file:
/home/roxanne/scratch/pbmc_granulocyte_sorted_10k/gex/STAR_Solo/S1/S1_Aligned.sortedByCoord.out.bam
/home/roxanne/scratch/pbmc_granulocyte_sorted_10k/atac/STAR_Solo/S16/S16_Aligned.sortedByCoord.out.bam

bc_path_file:
/home/roxanne/scratch/pbmc_granulocyte_sorted_10k/gex/STAR_Solo/S1/S1_Solo.out/Gene/filtered/barcodes.tsv
/home/roxanne/scratch/pbmc_granulocyte_sorted_10k/atac/STAR_Solo/S16/S16_Solo.out/Gene/filtered/barcodes.tsv

```

Should each donor be processed separately in MATES, or is it possible to include paths for all donors in a single `sample_list_file`, `bam_path_file`, and `bc_path_file`?

Your advice on how to best handle this would be greatly appreciated.

Thank you so much for your time and assistance.

**Comment by Szym29** [comment]
Hi @Citugulia40 ,

Thank you again for your interest in using MATES.

> Should barcodes for scATAC-seq be extracted directly from the BAM file? If so, I noticed that this results in a much larger set of barcodes compared to the filtered scRNA-seq barcodes.

If you are using 10X multiome data, practically, you can simply use the filtered barcode from RNA for the corresponding ATAC sample. Because one cell will have the same barcode for ATAC and RNA after 10X Multiome sequencing. And you will only use those cells that have TEs from both RNA and ATAC sequences after TE quantifying. So in this case, simply using the filtered barcode from RNA of the same sample should be fine. 

If you are using the independent 10X ATAC-seq data, one quick solution is that you can use the barcodes produced by cellranger-atac. 

>Which barcode files would you recommend using for each modality to ensure compatibility and optimal performance with MATES?

I will recommend you to use filtered barcode files whenever possible. It can be generated by Starsolo or cellranger (including cellranger-atac, and cellranger multi). These filtered cells are more confident to use and less barcodes will reduce the software running time.

>Should each donor be processed separately in MATES, or is it possible to include paths for all donors in a single sample_list_file, bam_path_file, and bc_path_file?

Yes, you can put all the donors and bam files into one sample_list_file, bam_path_file, and bc_path_file. MATES will process each sample individually and generated individual h5ad files for each sample in the sample_list_file.txt. You can simply concatenate all output h5ad files after quantifying TEs. Here is an example:
```
sample_list_file:
donor1_scRNA
donor2_scRNA
donor3_scRNA
donor1_scATAC
donor2_scATAC
donor3_scATAC

bam_path_file:
donor1_scRNA.bam
donor2_scRNA.bam
donor3_scRNA.bam
donor1_scATAC.bam
donor2_scATAC.bam
donor3_scATAC.bam

bc_path_file:
donor1_scRNA_barcodes.tsv
donor2_scRNA_barcodes.tsv
donor3_scRNA_barcodes.tsv
donor1_scATAC_barcodes.tsv
donor2_scATAC_barcodes.tsv
donor3_scATAC_barcodes.tsv
```

I hope these help & we are keep working to improve the stability and efficiency of MATES.

Thanks,
Yumin
